//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int Id_login { get; set; }
        public int id_student { get; set; }
        public string password { get; set; }
        public string login { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
